server {
    listen 80;
    listen [::]:80;
    server_name dsh.aitreez.com;

    root /opt/dsh-plugins-store/current;
    index index.html;

    location ^~ /.well-known/acme-challenge/ {
        root /var/www/certbot;
        default_type text/plain;
        try_files $uri =404;
    }

    location / {
        try_files $uri.html $uri/index.html $uri =404;
    }
}
