server {
    listen 80;
    listen [::]:80;
    server_name dsh.aitreez.com;

    location ^~ /.well-known/acme-challenge/ {
        root /var/www/certbot;
        default_type text/plain;
        try_files $uri =404;
    }

    location / {
        return 301 https://dshmk.com$request_uri;
    }
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name dsh.aitreez.com;

    ssl_certificate /etc/letsencrypt/live/dsh.aitreez.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/dsh.aitreez.com/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    add_header Strict-Transport-Security "max-age=31536000" always;
    location = /catalog.json {
        return 301 https://api.dshmk.com/$is_args$args;
    }

    location / {
        return 301 https://dshmk.com$request_uri;
    }
}
